<a href="https://colab.research.google.com/github/lathikaprabhakaran127/CODSOFT/blob/main/locationrecommendation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')



from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer
from geopy.geocoders import Nominatim

import statsmodels.api as sm
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
from sklearn.cluster import KMeans
df = pd.read_csv('/content/locations (1).csv',sep=',')

In [ ]:
#geopy in action
country = 'India'
city_names = df['location']

longitude =[]
latitude =[]
geolocator = Nominatim(user_agent="Trips")

for c in city_names.values:
    location = geolocator.geocode(c+','+ country)
    latitude.append(location.latitude)
    longitude.append(location.longitude)

In [ ]:
df['latitude']=latitude
df['longitude']=longitude

In [38]:
l2=df.iloc[:,-1:-3:-1]
l2

    loc_clusters  longitude
0              1  74.820444
1              2  70.802838
2              2  73.854454
3              0  77.590082
4              4  78.474061
5              4  81.373285
6              1  80.934600
7              3  86.974659
8              3  86.202958
9              3  91.282382
10             2  73.790236
11             1  75.851601
12             1  77.708101
13             3  83.007629
14             1  80.321759
15             1  78.009816
16             1  78.157363
17             0  76.245444
18             0  75.373797
19             0  80.270186
20             0  78.114098
21             2  70.802838
22             2  73.854454
23             0  77.590082
24             4  78.474061
25             4  81.373285
26             1  80.934600
27             3  86.974659
28             3  86.202958
29             0  80.270186

In [39]:
kmeans=KMeans(5)
kmeans.fit(l2)

identified_clusters = kmeans.fit_predict(l2)
identified_clusters = list(identified_clusters)
identified_clusters

[0,
 3,
 3,
 0,
 2,
 2,
 4,
 1,
 1,
 1,
 3,
 0,
 0,
 2,
 4,
 0,
 0,
 0,
 0,
 4,
 0,
 3,
 3,
 0,
 2,
 2,
 4,
 1,
 1,
 4]

In [ ]:
df['loc_clusters'] = identified_clusters
df

      location   latitude  longitude  loc_clusters
0     Srinagar  34.074744  74.820444             1
1       Rajkot  22.305326  70.802838             2
2         Pune  18.521428  73.854454             2
3    Bengaluru  12.976794  77.590082             0
4    Hyderabad  17.360589  78.474061             4
5       Bhilai  21.212068  81.373285             4
6      Lucknow  26.838100  80.934600             1
7      Asansol  23.687130  86.974659             3
8   Jamshedpur  22.801519  86.202958             3
9     Agartala  23.831238  91.282382             3
10      Nashik  20.011247  73.790236             2
11    Ludhiana  30.909016  75.851601             1
12      Meerut  28.982653  77.708101             1
13    Varanasi  25.335649  83.007629             3
14      Kanpur  26.460914  80.321759             1
15        Agra  27.175255  78.009816             1
16     Gwalior  26.203725  78.157363             1
17       Kochi   9.967428  76.245444             0
18      Kannur  11.876384  75.373797             0
19     Chennai  13.083694  80.270186             0
20     Madurai   9.926115  78.114098             0
21      Rajkot  22.305326  70.802838             2
22        Pune  18.521428  73.854454             2
23   Bengaluru  12.976794  77.590082             0
24   Hyderabad  17.360589  78.474061             4
25      Bhilai  21.212068  81.373285             4
26     Lucknow  26.838100  80.934600             1
27     Asansol  23.687130  86.974659             3
28  Jamshedpur  22.801519  86.202958             3
29     Chennai  13.083694  80.270186             0

In [37]:

input_city = input("Enter a city name:")
cluster = df.loc[df['location'] == input_city, 'loc_clusters']
cluster
cluster = cluster.iloc[0]
cities = df.loc[df['loc_clusters']==cluster,'location']
cities

for c in range(len(cities)):
  if cities.iloc[c]== input_city:
       continue
  else:
    print(cities.iloc[c])

Enter a city name:Lucknow
Srinagar
Ludhiana
Meerut
Kanpur
Agra
Gwalior